### ISSUE TITLE
Mojo-UserAgent-SecureServer-0.03 has started failing test

### ISSUE THREAD

**Issue by andk** [jhthorsen/mojo-useragent-secureserver#2]
Sample fail report: http://www.cpantesters.org/cpan/report/86f0adea-7861-11ec-a584-f533227d911e
This was the first fail report on 2022-01-18. Maybe some certificate has expired?

**Comment by jhthorsen** [comment]
Wow! I forgot to specify "days" when I generated the test certificate.

Thank you.
